export const accountTypes = [
    {value: 1, label: 'Managed Portfolio'},
    {value: 3, label: 'ISA'},
]
export const titles = [
    {value: 1, label: 'Mr'},
    {value: 2, label: 'Mrs'},
    {value: 3, label: 'Miss'},
    {value: 4, label: 'Ms'},
    {value: 5, label: 'Dame'},
    {value: 6, label: 'Doctor'},
    {value: 7, label: 'Lady'},
    {value: 8, label: 'Lord'},
    {value: 9, label: 'Professor'},
    {value: 10, label: 'Reverend'},
    {value: 11, label: 'Sir'}
];

export const maritialStatus = [
    {value: 1, label: 'Single'},
    {value: 2, label: 'Married'},
    {value: 3, label: 'Widowed'},
    {value: 4, label: 'Divorced'},
];

export const gender = [
    {value: 1, label: 'Male'},
    {value: 2, label: 'Female'},
];

export const green_card_holder = [
    {value: 1, label: 'No'},
    {value: 2, label: 'Yes'},
];

export const employment_type = [
    {value: 1, label: 'Employed'},
    {value: 2, label: 'Self-Employed'},
    {value: 3, label: 'Retired'},
    {value: 4, label: 'Unemployed'},
    {value: 5, label: 'Student'},
    {value: 6, label: 'Home Maker'}
];


export const nature_of_business = [{value: 1, label: 'Agriculture'},
    {value: 2, label: 'Mining'},
    {value: 3, label: 'Construction'},
    {value: 4, label: 'Manufacturing'},
    {value: 5, label: 'Transportation'},
    {value: 6, label: 'Wholesale/Distributors'},
    {value: 7, label: 'Retail'},
    {value: 8, label: 'Finance, Insurance & Real Estate'},
    {value: 9, label: 'Services'},
    {value: 10, label: 'Public Admin'},
    {value: 11, label: 'Others.'}
]

export const net_worth = [
    {value: 1, label: '< 20K'},
    {value: 2, label: '20K – 50K'},
    {value: 3, label: '50K – 75K'},
    {value: 4, label: '75K – 250K'},
    {value: 5, label: '250K – 500K'},
    {value: 6, label: '500K – 1M'},
    {value: 7, label: '1M – 2M'},
    {value: 8, label: '2M – 5M'},
    {value: 9, label: '5M – 10M'},
    {value: 10, label: '10M – 25M'},
    {value: 11, label: '25M - 30M'},
    {value: 12, label: '30M – 50M'},
    {value: 13, label: '>50M'}];

export const liquid_net_income = [
    {value: 1, label: '< 20K'},
    {value: 2, label: '20K – 50K'},
    {value: 3, label: '50K – 75K'},
    {value: 4, label: '75K – 100K'},
    {value: 5, label: '100K – 250K'},
    {value: 6, label: '250K – 500K'},
    {value: 7, label: '500K – 1M'},
    {value: 8, label: '1M – 5M'},
    {value: 9, label: '>5M'}]

export const annual_net_income = [
    {value: 1, label: '< 40K'},
    {value: 2, label: '40K – 45K'},
    {value: 3, label: '45K – 50K'},
    {value: 4, label: '50K – 100K'},
    {value: 5, label: '100K – 150K'},
    {value: 6, label: '150K – 200K'},
    {value: 7, label: '200K – 250K'},
    {value: 8, label: '250K – 500K'},
    {value: 9, label: '> 1M'}]

export const total_assets = [
    {value: 1, label: '< 20K'},
    {value: 2, label: '20K – 50K'},
    {value: 3, label: '50K – 75K'},
    {value: 4, label: '75K – 250K'},
    {value: 5, label: '250K – 500K'},
    {value: 6, label: '500K – 1M'},
    {value: 7, label: '1M – 2M'},
    {value: 8, label: '2M – 5M'},
    {value: 9, label: '5M – 10M'},
    {value: 10, label: '10M – 25M'},
    {value: 11, label: '25M - 30M'},
    {value: 12, label: '30M – 50M'},
    {value: 13, label: '>50M'}]

export const specific_goal = [
    {value: 1, label: 'Capital Preservation'},
    {value: 2, label: 'Capital Appreciation'},
    {value: 3, label: 'Current Income'},
    {value: 4, label: 'Total return'}]

export const risk_level = [
    {value: 1, label: 'Risk Level 1'},
    {value: 2, label: ' Risk Level 2 '},
    {value: 3, label: 'Risk Level 3 '},
    {value: 4, label: 'Risk Level 4'},
    {value: 5, label: 'Risk Level 5'},
    {value: 6, label: 'Risk Level 6'},
    {value: 7, label: 'Risk Level 7'}]

export const modelPortfolio = [
    {value: 1, label: 'Growth Portfolio'},
    {value: 2, label: ' High Growth Portfolio '},
    {value: 3, label: 'Conservative Portfolio'}]

export const countries = [
    {value: "UK", label: 'United Kingdom'},
    {value: 'US', label: 'United States'},
    {value: 'AF', label: 'Afghanistan'},
    {value: 'AL', label: 'Albania'},
    {value: 'DZ', label: 'Algeria'},
    {value: 'AS', label: 'American Samoa'},
    {value: 'AD', label: 'Andorra'},
    {value: 'AO', label: 'Angola'},
    {value: 'AI', label: 'Anguilla'},
    {value: 'AQ', label: 'Antarctica'},
    {value: 'AG', label: 'Antigua and Barbuda'},
    {value: 'AR', label: 'Argentina'},
    {value: 'AM', label: 'Armenia'},
    {value: 'AW', label: 'Aruba'},
    {value: 'AU', label: 'Australia'},
    {value: 'AT', label: 'Austria'},
    {value: 'AZ', label: 'Azerbaijan'},
    {value: 'BS', label: 'Bahamas'},
    {value: 'BH', label: 'Bahrain'},
    {value: 'BD', label: 'Bangladesh'},
    {value: 'BB', label: 'Barbados'},
    {value: 'BY', label: 'Belarus'},
    {value: 'BE', label: 'Belgium'},
    {value: 'BZ', label: 'Belize'},
    {value: 'BJ', label: 'Benin'},
    {value: 'BM', label: 'Bermuda'},
    {value: 'BT', label: 'Bhutan'},
    {value: 'BO', label: 'Bolivia, Plurinational State of'},
    {value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba'},
    {value: 'BA', label: 'Bosnia and Herzegovina'},
    {value: 'BW', label: 'Botswana'},
    {value: 'BV', label: 'Bouvet Island'},
    {value: 'BR', label: 'Brazil'},
    {value: 'IO', label: 'British Indian Ocean Territory'},
    {value: 'BN', label: 'Brunei Darussalam'},
    {value: 'BG', label: 'Bulgaria'},
    {value: 'BF', label: 'Burkina Faso'},
    {value: 'BI', label: 'Burundi'},
    {value: 'KH', label: 'Cambodia'},
    {value: 'CM', label: 'Cameroon'},
    {value: 'CA', label: 'Canada'},
    {value: 'CV', label: 'Cape Verde'},
    {value: 'KY', label: 'Cayman Islands'},
    {value: 'CF', label: 'Central African Republic'},
    {value: 'TD', label: 'Chad'},
    {value: 'CL', label: 'Chile'},
    {value: 'CN', label: 'China'},
    {value: 'CX', label: 'Christmas Island'},
    {value: 'CC', label: 'Cocos (Keeling) Islands'},
    {value: 'CO', label: 'Colombia'},
    {value: 'KM', label: 'Comoros'},
    {value: 'CG', label: 'Congo'},
    {value: 'CD', label: 'Congo, the Democratic Republic of the'},
    {value: 'CK', label: 'Cook Islands'},
    {value: 'CR', label: 'Costa Rica'},
    {value: 'CI', label: 'C�te d\'Ivoire'},
    {value: 'HR', label: 'Croatia'},
    {value: 'CU', label: 'Cuba'},
    {value: 'CW', label: 'Cura�ao'},
    {value: 'CY', label: 'Cyprus'},
    {value: 'CZ', label: 'Czech Republic'},
    {value: 'DK', label: 'Denmark'},
    {value: 'DJ', label: 'Djibouti'},
    {value: 'DM', label: 'Dominica'},
    {value: 'DO', label: 'Dominican Republic'},
    {value: 'EC', label: 'Ecuador'},
    {value: 'EG', label: 'Egypt'},
    {value: 'SV', label: 'El Salvador'},
    {value: 'GQ', label: 'Equatorial Guinea'},
    {value: 'ER', label: 'Eritrea'},
    {value: 'EE', label: 'Estonia'},
    {value: 'ET', label: 'Ethiopia'},
    {value: 'FK', label: 'Falkland Islands (Malvinas)'},
    {value: 'FO', label: 'Faroe Islands'},
    {value: 'FJ', label: 'Fiji'},
    {value: 'FI', label: 'Finland'},
    {value: 'FR', label: 'France'},
    {value: 'GF', label: 'French Guiana'},
    {value: 'PF', label: 'French Polynesia'},
    {value: 'TF', label: 'French Southern Territories'},
    {value: 'GA', label: 'Gabon'},
    {value: 'GM', label: 'Gambia'},
    {value: 'GE', label: 'Georgia'},
    {value: 'DE', label: 'Germany'},
    {value: 'GH', label: 'Ghana'},
    {value: 'GI', label: 'Gibraltar'},
    {value: 'GR', label: 'Greece'},
    {value: 'GL', label: 'Greenland'},
    {value: 'GD', label: 'Grenada'},
    {value: 'GP', label: 'Guadeloupe'},
    {value: 'GU', label: 'Guam'},
    {value: 'GT', label: 'Guatemala'},
    {value: 'GG', label: 'Guernsey'},
    {value: 'GN', label: 'Guinea'},
    {value: 'GW', label: 'Guinea-Bissau'},
    {value: 'GY', label: 'Guyana'},
    {value: 'HT', label: 'Haiti'},
    {value: 'HM', label: 'Heard Island and McDonald Islands'},
    {value: 'VA', label: 'Holy See (Vatican City State)'},
    {value: 'HN', label: 'Honduras'},
    {value: 'HK', label: 'Hong Kong'},
    {value: 'HU', label: 'Hungary'},
    {value: 'IS', label: 'Iceland'},
    {value: 'IN', label: 'India'},
    {value: 'ID', label: 'Indonesia'},
    {value: 'IR', label: 'Iran, Islamic Republic of'},
    {value: 'IQ', label: 'Iraq'},
    {value: 'IE', label: 'Ireland'},
    {value: 'IM', label: 'Isle of Man'},
    {value: 'IL', label: 'Israel'},
    {value: 'IT', label: 'Italy'},
    {value: 'JM', label: 'Jamaica'},
    {value: 'JP', label: 'Japan'},
    {value: 'JE', label: 'Jersey'},
    {value: 'JO', label: 'Jordan'},
    {value: 'KZ', label: 'Kazakhstan'},
    {value: 'KE', label: 'Kenya'},
    {value: 'KI', label: 'Kiribati'},
    {value: 'KP', label: 'Korea, Democratic People\'s Republic of'},
    {value: 'KR', label: 'Korea, Republic of'},
    {value: 'KW', label: 'Kuwait'},
    {value: 'KG', label: 'Kyrgyzstan'},
    {value: 'LA', label: 'Lao People\'s Democratic Republic'},
    {value: 'LV', label: 'Latvia'},
    {value: 'LB', label: 'Lebanon'},
    {value: 'LS', label: 'Lesotho'},
    {value: 'LR', label: 'Liberia'},
    {value: 'LY', label: 'Libya'},
    {value: 'LI', label: 'Liechtenstein'},
    {value: 'LT', label: 'Lithuania'},
    {value: 'LU', label: 'Luxembourg'},
    {value: 'MO', label: 'Macao'},
    {value: 'MK', label: 'Macedonia, the former Yugoslav Republic of'},
    {value: 'MG', label: 'Madagascar'},
    {value: 'MW', label: 'Malawi'},
    {value: 'MY', label: 'Malaysia'},
    {value: 'MV', label: 'Maldives'},
    {value: 'ML', label: 'Mali'},
    {value: 'MT', label: 'Malta'},
    {value: 'MH', label: 'Marshall Islands'},
    {value: 'MQ', label: 'Martinique'},
    {value: 'MR', label: 'Mauritania'},
    {value: 'MU', label: 'Mauritius'},
    {value: 'YT', label: 'Mayotte'},
    {value: 'MX', label: 'Mexico'},
    {value: 'FM', label: 'Micronesia, Federated States of'},
    {value: 'MD', label: 'Moldova, Republic of'},
    {value: 'MC', label: 'Monaco'},
    {value: 'MN', label: 'Mongolia'},
    {value: 'ME', label: 'Montenegro'},
    {value: 'MS', label: 'Montserrat'},
    {value: 'MA', label: 'Morocco'},
    {value: 'MZ', label: 'Mozambique'},
    {value: 'MM', label: 'Myanmar'},
    {value: 'NA', label: 'Namibia'},
    {value: 'NR', label: 'Nauru'},
    {value: 'NP', label: 'Nepal'},
    {value: 'NL', label: 'Netherlands'},
    {value: 'NC', label: 'New Caledonia'},
    {value: 'NZ', label: 'New Zealand'},
    {value: 'NI', label: 'Nicaragua'},
    {value: 'NE', label: 'Niger'},
    {value: 'NG', label: 'Nigeria'},
    {value: 'NU', label: 'Niue'},
    {value: 'NF', label: 'Norfolk Island'},
    {value: 'MP', label: 'Northern Mariana Islands'},
    {value: 'NO', label: 'Norway'},
    {value: 'OM', label: 'Oman'},
    {value: 'PK', label: 'Pakistan'},
    {value: 'PW', label: 'Palau'},
    {value: 'PS', label: 'Palestinian Territory, Occupied'},
    {value: 'PA', label: 'Panama'},
    {value: 'PG', label: 'Papua New Guinea'},
    {value: 'PY', label: 'Paraguay'},
    {value: 'PE', label: 'Peru'},
    {value: 'PH', label: 'Philippines'},
    {value: 'PN', label: 'Pitcairn'},
    {value: 'PL', label: 'Poland'},
    {value: 'PT', label: 'Portugal'},
    {value: 'PR', label: 'Puerto Rico'},
    {value: 'QA', label: 'Qatar'},
    {value: 'RE', label: 'R�union'},
    {value: 'RO', label: 'Romania'},
    {value: 'RU', label: 'Russian Federation'},
    {value: 'RW', label: 'Rwanda'},
    {value: 'BL', label: 'Saint Barth�lemy'},
    {value: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha'},
    {value: 'KN', label: 'Saint Kitts and Nevis'},
    {value: 'LC', label: 'Saint Lucia'},
    {value: 'MF', label: 'Saint Martin (French part)'},
    {value: 'PM', label: 'Saint Pierre and Miquelon'},
    {value: 'VC', label: 'Saint Vincent and the Grenadines'},
    {value: 'WS', label: 'Samoa'},
    {value: 'SM', label: 'San Marino'},
    {value: 'ST', label: 'Sao Tome and Principe'},
    {value: 'SA', label: 'Saudi Arabia'},
    {value: 'SN', label: 'Senegal'},
    {value: 'RS', label: 'Serbia'},
    {value: 'SC', label: 'Seychelles'},
    {value: 'SL', label: 'Sierra Leone'},
    {value: 'SG', label: 'Singapore'},
    {value: 'SX', label: 'Sint Maarten (Dutch part)'},
    {value: 'SK', label: 'Slovakia'},
    {value: 'SI', label: 'Slovenia'},
    {value: 'SB', label: 'Solomon Islands'},
    {value: 'SO', label: 'Somalia'},
    {value: 'ZA', label: 'South Africa'},
    {value: 'GS', label: 'South Georgia and the South Sandwich Islands'},
    {value: 'SS', label: 'South Sudan'},
    {value: 'ES', label: 'Spain'},
    {value: 'LK', label: 'Sri Lanka'},
    {value: 'SD', label: 'Sudan'},
    {value: 'SR', label: 'Suriname'},
    {value: 'SJ', label: 'Svalbard and Jan Mayen'},
    {value: 'SZ', label: 'Swaziland'},
    {value: 'SE', label: 'Sweden'},
    {value: 'CH', label: 'Switzerland'},
    {value: 'SY', label: 'Syrian Arab Republic'},
    {value: 'TW', label: 'Taiwan, Province of China'},
    {value: 'TJ', label: 'Tajikistan'},
    {value: 'TZ', label: 'Tanzania, United Republic of'},
    {value: 'TH', label: 'Thailand'},
    {value: 'TL', label: 'Timor-Leste'},
    {value: 'TG', label: 'Togo'},
    {value: 'TK', label: 'Tokelau'},
    {value: 'TO', label: 'Tonga'},
    {value: 'TT', label: 'Trinidad and Tobago'},
    {value: 'TN', label: 'Tunisia'},
    {value: 'TR', label: 'Turkey'},
    {value: 'TM', label: 'Turkmenistan'},
    {value: 'TC', label: 'Turks and Caicos Islands'},
    {value: 'TV', label: 'Tuvalu'},
    {value: 'UG', label: 'Uganda'},
    {value: 'UA', label: 'Ukraine'},
    {value: 'United Arab Emirates', label: 'United Arab Emirates'},
    {value: 'UY', label: 'Uruguay'},
    {value: 'UZ', label: 'Uzbekistan'},
    {value: 'VU', label: 'Vanuatu'},
    {value: 'VE', label: 'Venezuela, Bolivarian Republic of'},
    {value: 'Vietnam', label: 'Vietnam'},
    {value: 'Virgin Islands, British', label: 'Virgin Islands, British'},
    {value: 'Virgin Islands, U.S.', label: 'Virgin Islands, U.S.'},
    {value: 'Wallis and Futuna', label: 'Wallis and Futuna'},
    {value: 'Western Sahara', label: 'Western Sahara'},
    {value: 'Zambia', label: 'Yemen'},
    {value: 'Zambia', label: 'Zambia'},
    {value: 'Zimbabwe', label: 'Zimbabwe'},
]
